// =============================================================
// Eddie's Showroom — fake data for the prototype
// In production, this comes from Supabase `vehicles`/`leads`/`settings` tables
// =============================================================

window.SHOWROOM_DATA = (function () {
  const vehicles = [
    {
      id: "v01",
      slug: "2022-rogue-sv-24490",
      year: 2022, make: "Nissan", model: "Rogue", trim: "SV",
      mileage: 28400, stock: "N4821A",
      ext_color: "Pearl White", int_color: "Charcoal",
      engine: "1.5L Turbo", transmission: "CVT", drive: "AWD",
      mpg_city: 27, mpg_hwy: 35,
      title_status: "Clean", carfax: "1-Owner, no accidents",
      section: "suvs",
      pricing_type: "sale", sale_price: 24490,
      tags: ["cpo", "one_owner", "hot_deal"],
      hero_hue: 230, hero_tone: "neutral",
      photos: 7,
      description_en: "Just got this Rogue in from a one-owner trade. Pearl White with charcoal cloth interior, 28k miles, AWD with the 1.5 turbo. Clean Carfax, no stories. Owner traded up to a Pathfinder so this one's been pampered. Great commuter and qualifies for our CPO program. Let's talk about the deal.",
      description_es: "Acabo de recibir este Rogue de un dueño anterior. Blanco perla con interior de tela charcoal, 28 mil millas, AWD con motor 1.5 turbo. Carfax limpio, sin historias. El dueño cambió a una Pathfinder así que esta camioneta está bien cuidada. Buena para el diario y califica para nuestro programa CPO. Vamos a platicar del trato.",
      status: "live", views: 142, posted_days: 4,
    },
    {
      id: "v02",
      slug: "2026-sentra-sv-lease-199",
      year: 2026, make: "Nissan", model: "Sentra", trim: "SV",
      mileage: 12, stock: "N5102",
      ext_color: "Gun Metallic", int_color: "Charcoal",
      engine: "2.0L 4-cyl", transmission: "CVT", drive: "FWD",
      mpg_city: 30, mpg_hwy: 39,
      title_status: "New", carfax: "Brand new",
      section: "specials",
      pricing_type: "lease", monthly_payment: 199, lease_term: 36, lease_down: 2999,
      tags: ["new_arrival", "lifetime_warranty", "first_car"],
      hero_hue: 220, hero_tone: "cool",
      photos: 6,
      description_en: "Brand new '26 Sentra SV — $199/mo for 36 months with $2,999 down. Gun metallic, charcoal cloth, all the good stuff: heated seats, NissanConnect, safety shield. Lifetime powertrain warranty. Solid first car or commuter. Text me to lock the rate.",
      description_es: "Sentra SV 2026 nuevito — $199 al mes por 36 meses con $2,999 de enganche. Gris metálico, interior charcoal, asientos con calefacción, NissanConnect, paquete de seguridad. Garantía de por vida del tren motriz. Buenísimo primer carro. Mándame mensaje para apartar la tasa.",
      status: "live", views: 267, posted_days: 1,
    },
    {
      id: "v03",
      slug: "2023-altima-sr-22890",
      year: 2023, make: "Nissan", model: "Altima", trim: "SR",
      mileage: 31200, stock: "N4798A",
      ext_color: "Scarlet Ember", int_color: "Charcoal Sport",
      engine: "2.5L 4-cyl", transmission: "CVT", drive: "FWD",
      mpg_city: 27, mpg_hwy: 39,
      title_status: "Clean", carfax: "2-Owner",
      section: "cars",
      pricing_type: "sale", sale_price: 22890,
      tags: ["cpo", "hot_deal"],
      hero_hue: 250, hero_tone: "cool",
      photos: 8,
      description_en: "'23 Altima SR — the sport trim with the paddle shifters and red/black sport seats. 31k miles, just had its 30k service. Scarlet Ember red, looks sharp in person. CPO eligible. Around $22.9k or let's talk numbers if you have a trade.",
      description_es: "Altima SR 2023 — la versión deportiva con paletas al volante y asientos rojo/negro. 31 mil millas, recién hecho su servicio de 30 mil. Rojo Scarlet Ember, se ve increíble en persona. Califica para CPO. Alrededor de $22,900 o platiquemos números si traes algo a cambio.",
      status: "live", views: 89, posted_days: 6,
    },
    {
      id: "v04",
      slug: "2019-civic-lx-14990",
      year: 2019, make: "Honda", model: "Civic", trim: "LX",
      mileage: 62100, stock: "T2201A",
      ext_color: "Aegean Blue", int_color: "Black",
      engine: "2.0L 4-cyl", transmission: "CVT", drive: "FWD",
      mpg_city: 30, mpg_hwy: 38,
      title_status: "Clean", carfax: "1-Owner",
      section: "under15k",
      pricing_type: "sale", sale_price: 14990,
      tags: ["one_owner", "first_car"],
      hero_hue: 200, hero_tone: "cool",
      photos: 5,
      description_en: "Civic LX trade-in — 62k miles, one owner, clean Carfax. Honda makes these things last forever. Perfect first car or stepping-stone commuter. Around $14,990 — let's get it done before it walks off the lot.",
      description_es: "Civic LX que entró de cambio — 62 mil millas, un dueño, Carfax limpio. Honda los hace para que duren. Primer carro perfecto. Alrededor de $14,990 — vamos cerrando antes de que se vaya.",
      status: "live", views: 198, posted_days: 9,
    },
    {
      id: "v05",
      slug: "2021-frontier-sv-29490",
      year: 2021, make: "Nissan", model: "Frontier", trim: "SV",
      mileage: 41800, stock: "N4855A",
      ext_color: "Boulder Gray", int_color: "Charcoal",
      engine: "3.8L V6", transmission: "9AT", drive: "4WD",
      mpg_city: 18, mpg_hwy: 24,
      title_status: "Clean", carfax: "1-Owner",
      section: "trucks",
      pricing_type: "sale", sale_price: 29490,
      tags: ["cpo", "one_owner"],
      hero_hue: 240, hero_tone: "neutral",
      photos: 8,
      description_en: "Frontier SV Crew Cab 4x4 — 41k miles, the redesigned body style with the 3.8 V6 and 9-speed. Boulder Gray, charcoal cloth, towing package. One owner, clean Carfax. Solid work truck or weekend hauler. CPO eligible.",
      description_es: "Frontier SV Crew Cab 4x4 — 41 mil millas, el modelo rediseñado con V6 3.8 y transmisión de 9 velocidades. Gris Boulder, interior charcoal, paquete de remolque. Un dueño, Carfax limpio. Buena troca de trabajo o de fin de semana. Califica para CPO.",
      status: "live", views: 156, posted_days: 3,
    },
    {
      id: "v06",
      slug: "2020-f150-xlt-32990",
      year: 2020, make: "Ford", model: "F-150", trim: "XLT",
      mileage: 54200, stock: "T2188A",
      ext_color: "Magnetic Gray", int_color: "Medium Earth Gray",
      engine: "5.0L V8", transmission: "10AT", drive: "4WD",
      mpg_city: 16, mpg_hwy: 22,
      title_status: "Clean", carfax: "2-Owner",
      section: "trucks",
      pricing_type: "sale", sale_price: 32990,
      tags: ["hot_deal"],
      hero_hue: 215, hero_tone: "neutral",
      photos: 7,
      description_en: "F-150 XLT SuperCrew 4x4 — 54k miles, 5.0 V8, towing package, bedliner already in. Trade-in from a regular customer who upgraded to a Titan. Around $32,990. Drive it home today.",
      description_es: "F-150 XLT SuperCrew 4x4 — 54 mil millas, V8 5.0, paquete de remolque, ya tiene bedliner. Cambio de un cliente que se pasó a una Titan. Alrededor de $32,990. Llévatela hoy.",
      status: "live", views: 121, posted_days: 7,
    },
    {
      id: "v07",
      slug: "2024-pathfinder-sl-39990",
      year: 2024, make: "Nissan", model: "Pathfinder", trim: "SL",
      mileage: 18900, stock: "N4901A",
      ext_color: "Super Black", int_color: "Charcoal Leather",
      engine: "3.5L V6", transmission: "9AT", drive: "AWD",
      mpg_city: 21, mpg_hwy: 27,
      title_status: "Clean", carfax: "1-Owner",
      section: "suvs",
      pricing_type: "sale", sale_price: 39990,
      tags: ["cpo", "one_owner", "featured"],
      hero_hue: 260, hero_tone: "dark",
      photos: 8,
      description_en: "Pathfinder SL — 18k miles, basically new. 3-row leather, captain's chairs in the second row, tow package, AWD. Super Black on charcoal. CPO eligible. This is my pick of the SUV lot this week.",
      description_es: "Pathfinder SL — 18 mil millas, prácticamente nueva. Tres filas, piel, asientos capitán en la segunda, paquete de remolque, AWD. Negro sobre charcoal. Califica para CPO. Mi favorita del lote esta semana.",
      status: "live", views: 312, posted_days: 2,
    },
    {
      id: "v08",
      slug: "2018-versa-s-9990",
      year: 2018, make: "Nissan", model: "Versa", trim: "S",
      mileage: 78400, stock: "N4720A",
      ext_color: "Fresh Powder", int_color: "Charcoal",
      engine: "1.6L 4-cyl", transmission: "5MT", drive: "FWD",
      mpg_city: 31, mpg_hwy: 39,
      title_status: "Clean", carfax: "2-Owner",
      section: "under15k",
      pricing_type: "sale", sale_price: 9990,
      tags: ["first_car"],
      hero_hue: 210, hero_tone: "light",
      photos: 5,
      description_en: "Versa S — under $10k, 5-speed manual for the folks who still drive stick. 78k miles, runs solid. Honest little commuter. No frills, just gets you there. Let's talk.",
      description_es: "Versa S — menos de $10 mil, manual de 5 velocidades para los que todavía manejan estándar. 78 mil millas, anda bien. Carrito honesto. Sin lujos, te lleva a donde vas. Platiquemos.",
      status: "live", views: 88, posted_days: 11,
    },
    {
      id: "v09",
      slug: "2026-rogue-sv-lease-289",
      year: 2026, make: "Nissan", model: "Rogue", trim: "SV",
      mileage: 8, stock: "N5188",
      ext_color: "Champagne Silver", int_color: "Charcoal",
      engine: "1.5L Turbo", transmission: "CVT", drive: "AWD",
      mpg_city: 28, mpg_hwy: 34,
      title_status: "New", carfax: "Brand new",
      section: "specials",
      pricing_type: "lease", monthly_payment: 289, lease_term: 36, lease_down: 3499,
      tags: ["new_arrival", "lifetime_warranty"],
      hero_hue: 225, hero_tone: "neutral",
      photos: 6,
      description_en: "Brand-new '26 Rogue SV AWD — $289/mo for 36, $3,499 down. Champagne Silver. The new face-lifted body. Lifetime powertrain warranty. Locks at this rate through end of month.",
      description_es: "Rogue SV AWD 2026 nuevita — $289 al mes por 36, $3,499 de enganche. Champagne Silver. El nuevo modelo rediseñado. Garantía de por vida. La tasa la apartas hasta fin de mes.",
      status: "live", views: 178, posted_days: 1,
    },
    {
      id: "v10",
      slug: "2022-kicks-sv-18490",
      year: 2022, make: "Nissan", model: "Kicks", trim: "SV",
      mileage: 34800, stock: "N4811A",
      ext_color: "Monarch Orange", int_color: "Charcoal",
      engine: "1.6L 4-cyl", transmission: "CVT", drive: "FWD",
      mpg_city: 31, mpg_hwy: 36,
      title_status: "Clean", carfax: "1-Owner",
      section: "cars",
      pricing_type: "sale", sale_price: 18490,
      tags: ["one_owner", "first_car"],
      hero_hue: 245, hero_tone: "neutral",
      photos: 6,
      description_en: "Kicks SV — that fun Monarch Orange w/ black roof. 34k miles, one owner. Tiny on gas, easy to park, surprisingly roomy. Around $18,490.",
      description_es: "Kicks SV — el naranja Monarch con techo negro. 34 mil millas, un dueño. Buenísimo en gasolina, fácil de estacionar. Alrededor de $18,490.",
      status: "live", views: 109, posted_days: 5,
    },
    {
      id: "v11",
      slug: "2023-titan-sv-apr-0",
      year: 2023, make: "Nissan", model: "Titan", trim: "SV",
      mileage: 42, stock: "N5044",
      ext_color: "Cardinal Red", int_color: "Charcoal",
      engine: "5.6L V8", transmission: "9AT", drive: "4WD",
      mpg_city: 16, mpg_hwy: 21,
      title_status: "New", carfax: "Brand new",
      section: "specials",
      pricing_type: "apr", apr_rate: 0, apr_term: 60, sale_price: 48990,
      tags: ["new_arrival", "lifetime_warranty"],
      hero_hue: 255, hero_tone: "neutral",
      photos: 7,
      description_en: "'23 Titan SV — 0% APR for 60 months on the leftover '23s. Cardinal Red, full 5.6 V8, tow ready. Lifetime PT warranty. Won't last at this rate.",
      description_es: "Titan SV 2023 — 0% APR por 60 meses en las que quedan. Rojo Cardinal, V8 5.6, lista para remolcar. Garantía de por vida. No durará a este precio.",
      status: "live", views: 245, posted_days: 4,
    },
    {
      id: "v12",
      slug: "2017-sentra-s-11490",
      year: 2017, make: "Nissan", model: "Sentra", trim: "S",
      mileage: 91200, stock: "N4680A",
      ext_color: "Aspen White", int_color: "Charcoal",
      engine: "1.8L 4-cyl", transmission: "CVT", drive: "FWD",
      mpg_city: 29, mpg_hwy: 37,
      title_status: "Clean", carfax: "3-Owner",
      section: "under15k",
      pricing_type: "sale", sale_price: 11490,
      tags: ["first_car"],
      hero_hue: 205, hero_tone: "light",
      photos: 5,
      description_en: "Sentra S — 91k miles, runs great. Honest first-car territory. Around $11,490, willing to talk if you're paying cash.",
      description_es: "Sentra S — 91 mil millas, anda muy bien. Buen primer carro. Alrededor de $11,490, hay platica si pagas en efectivo.",
      status: "live", views: 67, posted_days: 14,
    },
    {
      id: "v13",
      slug: "2021-murano-platinum-31490",
      year: 2021, make: "Nissan", model: "Murano", trim: "Platinum",
      mileage: 38900, stock: "N4870A",
      ext_color: "Deep Blue Pearl", int_color: "Cashmere Leather",
      engine: "3.5L V6", transmission: "CVT", drive: "AWD",
      mpg_city: 20, mpg_hwy: 28,
      title_status: "Clean", carfax: "1-Owner",
      section: "finds",
      pricing_type: "sale", sale_price: 31490,
      tags: ["cpo", "one_owner", "featured"],
      hero_hue: 230, hero_tone: "cool",
      photos: 8,
      description_en: "Murano Platinum — top trim, panoramic roof, cashmere leather, heated and cooled seats. Deep Blue Pearl that looks black until the sun hits. 38k, one owner, CPO eligible. This is the one I'd buy if my wife let me.",
      description_es: "Murano Platinum — la versión top, techo panorámico, piel cashmere, asientos con calefacción y aire. Azul profundo que se ve negro hasta que le pega el sol. 38 mil, un dueño, CPO. Esta me la quedaría yo si mi esposa me dejara.",
      status: "live", views: 198, posted_days: 8,
    },
    {
      id: "v14",
      slug: "2020-altima-platinum-cash-2000",
      year: 2020, make: "Nissan", model: "Altima", trim: "Platinum",
      mileage: 47200, stock: "N4799A",
      ext_color: "Pearl White Tricoat", int_color: "Charcoal Leather",
      engine: "2.0L VC-Turbo", transmission: "CVT", drive: "AWD",
      mpg_city: 25, mpg_hwy: 34,
      title_status: "Clean", carfax: "1-Owner",
      section: "finds",
      pricing_type: "cash_bonus", sale_price: 23990, cash_bonus: 2000,
      tags: ["cpo", "one_owner", "featured"],
      hero_hue: 235, hero_tone: "neutral",
      photos: 7,
      description_en: "Altima Platinum AWD with the VC-Turbo — rare combo. $2,000 cash bonus this week, brings it to about $21.9k. Pearl White tricoat, leather, all the toys. CPO eligible.",
      description_es: "Altima Platinum AWD con motor VC-Turbo — combo raro. $2,000 de bono esta semana, queda como en $21,900. Blanco perla tricoat, piel, todos los juguetes. Califica para CPO.",
      status: "live", views: 134, posted_days: 6,
    },
  ];

  const leads = [
    {
      id: "L01", name: "Maria L.", phone: "(402) 555-0188",
      vehicle_id: "v01", vehicle_label: "2022 Rogue SV",
      source: "chat", utm: "facebook", language: "en",
      intent: "browse", budget: "$25k", timeline: "this week", credit: "good",
      status: "new", minutes_ago: 12,
      transcript: [
        { from: "bot", text: "Hi! I see you're checking out the 2022 Rogue SV. Want me to lock in $24,490 or schedule a quick visit?" },
        { from: "user", text: "Is this still available?" },
        { from: "bot", text: "Yep, still here on the lot. Want me to set a time for you to come see it?" },
        { from: "user", text: "Tomorrow afternoon?" },
        { from: "bot", text: "Easy. What's the best phone for Eddie to text you?" },
        { from: "user", text: "(402) 555-0188" },
      ],
      notes: "",
    },
    {
      id: "L02", name: "James K.", phone: "(402) 555-0231", email: "jkay@gmail.com",
      vehicle_id: "v02", vehicle_label: "2026 Sentra Lease",
      source: "credit_app", utm: "instagram", language: "en",
      intent: "finance", budget: "$200/mo", timeline: "this month", credit: "fair",
      status: "contacted", minutes_ago: 122,
      transcript: [],
      credit_data: { income: "$3,800/mo", employer: "Werner Enterprises", residence: "rent" },
      notes: "Called him at 2pm — said he'd come by Saturday morning.",
    },
    {
      id: "L03", name: "Carlos R.", phone: "(402) 555-0144",
      vehicle_id: "v05", vehicle_label: "2021 Frontier SV",
      source: "chat", utm: "facebook", language: "es",
      intent: "test_drive", budget: "$30k", timeline: "this week", credit: "excellent",
      status: "appointment_set", minutes_ago: 280,
      transcript: [
        { from: "bot", text: "¡Hola! Veo que andas mirando la Frontier SV. ¿Quieres apartarla o agendar una visita?" },
        { from: "user", text: "Quiero verla mañana" },
      ],
      notes: "Sábado 10am confirmado.",
    },
    {
      id: "L04", name: "Tasha B.", phone: "(402) 555-0299",
      vehicle_id: null, vehicle_label: "General — SUVs under $20k",
      source: "chat", utm: "direct", language: "en",
      intent: "browse", budget: "$18k", timeline: "this month", credit: "good",
      status: "new", minutes_ago: 38,
      transcript: [
        { from: "bot", text: "Hi! I'm here to help you find a car at Nissan of Omaha. What brings you in today?" },
        { from: "user", text: "Looking for an SUV under 20k" },
      ],
      notes: "",
    },
    {
      id: "L05", name: "Andre P.", phone: "(402) 555-0411",
      vehicle_id: "v06", vehicle_label: "2020 F-150 XLT",
      source: "chat", utm: "facebook", language: "en",
      intent: "trade", budget: "—", timeline: "this week", credit: "good",
      status: "new", minutes_ago: 4,
      transcript: [
        { from: "user", text: "Got a 2015 Tacoma to trade. Worth checking out the F-150?" },
      ],
      notes: "",
      trade_data: { year: 2015, make: "Toyota", model: "Tacoma", miles: 119000 },
    },
    {
      id: "L06", name: "Devon W.", phone: "(402) 555-0567",
      vehicle_id: "v07", vehicle_label: "2024 Pathfinder SL",
      source: "credit_app", utm: "instagram", language: "en",
      intent: "finance", budget: "$500/mo", timeline: "this week", credit: "good",
      status: "closed_won", minutes_ago: 1620,
      transcript: [],
      credit_data: { income: "$5,400/mo", employer: "Mutual of Omaha", residence: "own" },
      notes: "Delivered Wed. Sold!",
    },
  ];

  const settings = {
    display_name: "Eddie Diaz",
    role: "Sales Specialist",
    dealership: "Nissan of Omaha",
    address: "17410 Burt St, Omaha, NE 68118",
    phone: "(402) 555-0123",
    phone_e164: "+14025550123",
    email: "eddie@eddie-cars.com",
    languages: ["English", "Español"],
    sections_enabled: { under15k: true, cars: true, suvs: true, trucks: true, finds: true, specials: true },
    about_en: "I've been selling cars in Omaha for 11 years, the last 4 here at Nissan of Omaha. I work in Bay 4. I'm bilingual EN/ES, I reply to texts in 5 minutes during work hours, and I don't do high-pressure stuff. I'd rather you buy the right car than any car. Pull up. Coffee's on me.",
    about_es: "Llevo 11 años vendiendo carros en Omaha, los últimos 4 aquí en Nissan of Omaha. Trabajo en el Bay 4. Hablo inglés y español, contesto los mensajes en 5 minutos durante horas de trabajo, y no le hago a la presión. Prefiero que te lleves el carro correcto y no cualquiera. Pásale. El café va por mi cuenta.",
    stats: { years: 11, sold_lifetime: 1840, repeat_customers: "62%" },
  };

  const sections = [
    { id: "under15k", en: "Under $15K", es: "Menos de $15K", tag_en: "Honest first cars", tag_es: "Primer carro honesto" },
    { id: "cars",     en: "Cars",       es: "Carros",       tag_en: "Sedans + hatchbacks", tag_es: "Sedanes + hatchbacks" },
    { id: "suvs",     en: "SUVs",       es: "SUVs",         tag_en: "Family + commute", tag_es: "Familiar + diario" },
    { id: "trucks",   en: "Trucks",     es: "Trocas",       tag_en: "Work + weekend", tag_es: "Trabajo + fin de semana" },
    { id: "finds",    en: "Special Finds", es: "Hallazgos Especiales", tag_en: "Eddie's picks this week", tag_es: "Mis picks de esta semana" },
    { id: "specials", en: "New Specials", es: "Especiales Nuevos", tag_en: "Lease + APR deals", tag_es: "Renta + APR" },
  ];

  const t = {
    en: {
      text_eddie: "Text Eddie",
      hero_kicker: "Bay 4 · Nissan of Omaha",
      hero_h1_a: "Eddie. Bay 4.",
      hero_h1_b: "Coffee in hand.",
      hero_lede: "I curate a small set of cars I can stand behind. Used, new, lease specials. If it's on this page, I'd put my name on it.",
      stat_years: "Years in the business",
      stat_sold: "Cars sold, lifetime",
      stat_repeat: "Customers who came back",
      trust_warranty: "Lifetime PT Warranty",
      trust_buyhome: "Buy@Home delivery",
      trust_bilingual: "Bilingual EN / ES",
      trust_reply: "5-min text replies",
      sort_featured: "Featured",
      sort_price_up: "Price ↑",
      sort_price_down: "Price ↓",
      sort_newest: "Newest",
      sort_low_miles: "Low miles",
      credit_h: "Get pre-approved in 60 seconds",
      credit_p: "Soft pull. Doesn't ding your credit. I see it the moment you submit.",
      trade_h: "What's your trade worth?",
      trade_p: "Snap a few pics, tell me the miles. I'll text you a real number, not a guess.",
      drive_h: "Book a test drive",
      drive_p: "Pick a time. I'll have it pulled up front with the AC running and a coffee.",
      about_h: "About me",
      footer_disclaim: "Personal page operated by Eddie Diaz, sales specialist at Nissan of Omaha. All vehicles subject to prior sale. Pricing excludes tax, title, and dealer fees. Photos may be representative.",
    },
    es: {
      text_eddie: "Mándale mensaje",
      hero_kicker: "Bay 4 · Nissan of Omaha",
      hero_h1_a: "Eddie. Bay 4.",
      hero_h1_b: "Café en mano.",
      hero_lede: "Curo un grupo chico de carros con los que me siento bien. Usados, nuevos, especiales de renta. Si está en esta página, le pongo mi nombre.",
      stat_years: "Años en el negocio",
      stat_sold: "Carros vendidos en total",
      stat_repeat: "Clientes que regresan",
      trust_warranty: "Garantía de por vida",
      trust_buyhome: "Entrega a domicilio",
      trust_bilingual: "Bilingüe EN / ES",
      trust_reply: "Respondo en 5 min",
      sort_featured: "Destacados",
      sort_price_up: "Precio ↑",
      sort_price_down: "Precio ↓",
      sort_newest: "Nuevos",
      sort_low_miles: "Pocas millas",
      credit_h: "Pre-aprobación en 60 segundos",
      credit_p: "Soft pull. No afecta tu crédito. Lo veo apenas lo mandas.",
      trade_h: "¿Cuánto vale tu carro?",
      trade_p: "Mándame fotos y las millas. Te texteo un número real, no adivinanza.",
      drive_h: "Agenda un test drive",
      drive_p: "Pícale una hora. Lo tengo afuera con el aire prendido y un café listo.",
      about_h: "Sobre mí",
      footer_disclaim: "Página personal operada por Eddie Diaz, especialista de ventas en Nissan of Omaha. Vehículos sujetos a venta previa. Precios sin impuestos, título ni cargos. Fotos representativas.",
    },
  };

  return { vehicles, leads, settings, sections, t };
})();
